### ISSUE TITLE
error code: 32602 is throwed when request address from the snap

### ISSUE THREAD

**Issue by liangping** [cosmos/snap#16]
```js

        await ethereum.request({
            method: 'wallet_invokeSnap',
            params: {
                snapId: 'npm:@cosmsnap/snap',
                request: {
                    method: 'initialize',
                },
            },
        });

        const address = await window.ethereum.request({
            method: 'wallet_invokeSnap',
            params: {
                snapId: 'npm:@cosmsnap/snap',
                request: {
                    method: 'getChainAddress',
                    param: {
                        chain_id: 'cosmoshub-4',
                    }
                },
            },
        });
```

```json
{ "code": -32602, "message": "Must specify a valid JSON-RPC request object as single parameter.", "stack": "{\n \"code\": -32602,\n \"message\": \"Must specify a valid JSON-RPC request object as single parameter.\",\n \"stack\": \"Error: Must specify a valid JSON-RPC request object as single parameter.\\n at new n (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:10940)\\n at o (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:13880)\\n at Object.invalidParams (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:14387)\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:437942\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329734\\n at Generator.next (<anonymous>)\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329322\\n at new Promise (<anonymous>)\\n at s (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329067)\\n at c (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329693)\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:425536\\n at v._executeRestrictedMethod (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:347586)\\n at v.<anonymous> (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:357289)\\n at Generator.next (<anonymous>)\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:356749\\n at new Promise (<anonymous>)\\n at s (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:356494)\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:357186\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:37941\\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36950\\n at new Promise (<anonymous>)\\n at o._runMiddleware (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36607)\\n at o._runAllMiddleware (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36513)\\n at async o._processRequest (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36294)\\n at async o._handle (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36135)\"\n}\n at new n (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:10940)\n at o (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:13880)\n at Object.invalidParams (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-3.js:16:14387)\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:437942\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329734\n at Generator.next (<anonymous>)\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329322\n at new Promise (<anonymous>)\n at s (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329067)\n at c (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:329693)\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:425536\n at v._executeRestrictedMethod (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:347586)\n at v.<anonymous> (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:357289)\n at Generator.next (<anonymous>)\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:356749\n at new Promise (<anonymous>)\n at s (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:356494)\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-0.js:1:357186\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:37941\n at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36950\n at new Promise (<anonymous>)\n at o._runMiddleware (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36607)\n at o._runAllMiddleware (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36513)\n at async o._processRequest (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36294)\n at async o._handle (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/common-4.js:19:36135)" }.
```

**Comment by schnetzlerjoe** [comment]
@liangping The `param` key should be `params`. Also, make sure you are running Metamask Flask in a browser that does not have Metamask installed. They conflict in many instances!
